CREATE DATABASE ECOM; -- creating database 
USE ECOM; -- using the database

-- creating tables
-- customers

CREATE TABLE CUSTOMERS(
cUST_ID VARCHAR(255),
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(255),
EMAIL VARCHAR(250),
GENDER ENUM("Male","Female","Others"),
PHONE VARCHAR(10),
ANNUAL_INCOME DECIMAL(10,2));

Alter table CUSTOMERS 
RENAME COLUMN cUST_ID TO CUST_ID ;

SELECT *
FROM CUSTOMERS;

DESCRIBE CUSTOMERS;

-- SALES TABLE

CREATE TABLE PRODUCTS(
PROD_ID INT PRIMARY KEY,
PROD_NAME VARCHAR(255) UNIQUE,
UNIT_PRICE DECIMAL(10,2),
CATEGORY VARCHAR(200));

ALTER TABLE CUSTOMERS
MODIFY COLUMN CUST_ID VARCHAR(255) PRIMARY KEY;

DESCRIBE CUSTOMERS;

CREATE TABLE SALES(
QUANTITY INT,
SALES DECIMAL(9,2),
CUST_ID VARCHAR(200),
PROD_ID INT,
DISCOUNT DECIMAL(3,2),
LOCATION CHAR(50),
ORDER_DATE DATE,
DELIVERY_DATE DATE,
PROFIT DECIMAL(9,2));

ALTER TABLE SALES
ADD constraint foreign key (CUST_ID) references CUSTOMERS(CUST_ID),
ADD constraint foreign key (PROD_ID) references PRODUCTS(PROD_ID);

-- INSERTING DATA ON CUSTOMERS
 
INSERT INTO CUSTOMERS(CUST_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PHONE,ANNUAL_INCOME)
VALUES
("CUST_101","Veena","Kutty","veena.kutty@gmail.com","Female","1234567890",55000);

Insert into CUSTOMERS values
("CUST_102","Hitesh","Hirwani","hitesh.hirwani@gmail.com","Male","0987654321",100000),
("Cust_103","Nishika","Chandwani","nishika.chandwani@gmail.com","Female","9509509500",100000),
("Cust_104","Kanisha","Chandwani","kanisha.chandwani@gmail.com,","Female","3030303030",90000),
("Cust_105","Girish","Motwani","girish.motwani@gmail.com","Male","1010101010",95000);

SELECT *
FROM CUSTOMERS;

SELECT FIRST_NAME,GENDER
FROM CUSTOMERS;

-- Modify Tables

ALTER TABLE SALES
ADD COLUMN SALE_ID INT auto_increment primary key;

ALTER TABLE CUSTOMERS
MODIFY COLUMN FIRST_NAME VARCHAR(255) NOT NULL;

ALTER TABLE PRODUCTS
MODIFY COLUMN PROD_NAME VARCHAR(255) NOT NULL,
MODIFY COLUMN UNIT_PRICE DECIMAL(10,2) NOT NULL;

ALTER TABLE PRODUCTS
ADD CONSTRAINT CHECK (UNIT_PRICE > 0);

ALTER TABLE SALES
ADD CONSTRAINT CHECK (QUANTITY > 0);

ALTER TABLE SALES
ADD CONSTRAINT CHECK (DISCOUNT BETWEEN 0 AND 1);

CREATE TABLE PAYMENTS(
PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
ORDER_ID INT NOT NULL,
PAYMENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
PAYMENT_MODE ENUM ('UPI','Card','Net Banking','COD'),
PAYMENT_AMOUNT DECIMAL(10,2) NOT NULL,
PAYMENT_STATUS ENUM ('Pending','Completed','Failed','Refunded') DEFAULT 'Pending');

CREATE TABLE ORDERS(
ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
CUST_ID VARCHAR(255),
ORDER_STATUS ENUM ('Pending','Shipped','Delivered','Cancelled','Confirmed','On The Way') DEFAULT 'Pending',
SHIPPING_ADDRESS VARCHAR(255),
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID));

ALTER TABLE PAYMENTS
ADD CONSTRAINT 
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);

-- Insert data

SET FOREIGN_KEY_CHECKS = 0;

select * from products;

INSERT INTO PRODUCTS VALUES
(1001,"Men's T-Shirt",400,"Clothing"),
(1002,"Shoes",1500,"Foot-Wear"),
(1003,"Apple Watch",68000,"Electronics"),
(1004,"Table",15000,"Furniture"),
(1005,"Heels",400,"Foot-Waer"),
(1006,"Samsung S26 Ultra",135000,"Electronics");

INSERT INTO ORDERS value
(1101,'CUST-103','Pending','Mumbai');

INSERT INTO ORDERS(CUST_ID,ORDER_STATUS,SHIPPING_ADDRESS) VALUES
('CUST-104','Delivered','Pune'),
('CUST-101','On The Way','Delhi'),
('CUST-102','Confirmed','Nagpur'),
('CUST-101','Cancelled','Nashik'),
('CUST-105','Shipped','Gurgaon'),
('CUST-101','Delivered','Haryana'),
('CUST-104','Cancelled','Pune'),
('CUST-102','On The Way','Nagpur'),
('CUST-102','Shipped','Mumbai');