CREATE DATABASE ECOM; -- creating database 
USE ECOM; -- using the database

-- creating tables
-- customers

CREATE TABLE CUSTOMERS(
cUST_ID VARCHAR(255),
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(255),
EMAIL VARCHAR(250),
GENDER ENUM("Male","Female","Others"),
PHONE VARCHAR(10),
ANNUAL_INCOME DECIMAL(10,2));

Alter table CUSTOMERS 
RENAME COLUMN cUST_ID TO CUST_ID ;

SELECT *
FROM CUSTOMERS;

DESCRIBE CUSTOMERS;
