CREATE DATABASE ECOM; -- creating database 
USE ECOM; -- using the database

-- creating tables
-- customers

CREATE TABLE CUSTOMERS(
cUST_ID VARCHAR(255),
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(255),
EMAIL VARCHAR(250),
GENDER ENUM("Male","Female","Others"),
PHONE VARCHAR(10),
ANNUAL_INCOME DECIMAL(10,2));

Alter table CUSTOMERS 
RENAME COLUMN cUST_ID TO CUST_ID ;

SELECT *
FROM CUSTOMERS;

DESCRIBE CUSTOMERS;

-- SALES TABLE

CREATE TABLE PRODUCTS(
PROD_ID INT PRIMARY KEY,
PROD_NAME VARCHAR(255) UNIQUE,
UNIT_PRICE DECIMAL(10,2),
CATEGORY VARCHAR(200));

ALTER TABLE CUSTOMERS
MODIFY COLUMN CUST_ID VARCHAR(255) PRIMARY KEY;

DESCRIBE CUSTOMERS;

CREATE TABLE SALES(
QUANTITY INT,
SALES DECIMAL(9,2),
CUST_ID VARCHAR(200),
PROD_ID INT,
DISCOUNT DECIMAL(3,2),
LOCATION CHAR(50),
ORDER_DATE DATE,
DELIVERY_DATE DATE,
PROFIT DECIMAL(9,2));

ALTER TABLE SALES
ADD constraint foreign key (CUST_ID) references CUSTOMERS(CUST_ID),
ADD constraint foreign key (PROD_ID) references PRODUCTS(PROD_ID);

-- INSERTING DATA ON CUSTOMERS
 
INSERT INTO CUSTOMERS(CUST_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PHONE,ANNUAL_INCOME)
VALUES
("CUST_101","Veena","Kutty","veena.kutty@gmail.com","Female","1234567890",55000);

Insert into CUSTOMERS values
("CUST_102","Hitesh","Hirwani","hitesh.hirwani@gmail.com","Male","0987654321",100000),
("Cust_103","Nishika","Chandwani","nishika.chandwani@gmail.com","Female","9509509500",100000),
("Cust_104","Kanisha","Chandwani","kanisha.chandwani@gmail.com,","Female","3030303030",90000),
("Cust_105","Girish","Motwani","girish.motwani@gmail.com","Male","1010101010",95000);

SELECT *
FROM CUSTOMERS;

SELECT FIRST_NAME,GENDER
FROM CUSTOMERS;